//REGISTER TYPES
export const REGISTER_SUCCESS = `REGISTER_SUCCESS`
export const REGISTER_FAIL = `REGISTER_FAIL`
//LOGIN TYPES
export const LOGIN_SUCCESS = `LOGIN_SUCCESS`
export const LOGIN_FAIL = `LOGIN_FAIL`
export const LOGOUT_SUCCESS=`LOGOUT_SUCCESS`
//USER TYPES
export const GET_USER_SUCCESS=`GET_USER_SUCCESS`
export const GET_USER_FAIL=`GET_USER_FAIL`
//CHANGE PASSWORD TYPES
export const CHANGE_PASSWORD_REQUEST=`CHANGE_PASSWORD_REQUEST`
export const CHANGE_PASSWORD_SUCCESS=`CHANGE_PASSWORD_SUCCESS`
export const CHANGE_PASSWORD_FAIL=`CHANGE_PASSWORD_FAIL`
// STORE TYPES
export const ADD_STORE_REQUEST = `ADD_STORE_REQUEST`
export const ADD_STORE_SUCCESS=`ADD_STORE_SUCCESS`
export const ADD_STORE_FAIL=`ADD_STORE_FAIL`
//Profile comments
export const FETCH_PROFILE_COMMENTS_SUCCESS=`FETCH_PROFILE_COMMENTS_SUCCESS`
export const FETCH_PROFILE_COMMENTS_FAIL=`FETCH_PROFILE_COMMENTS_FAIL`
