//FETCHNG STORE DATA
export const FETCH_STORE_SUCCESS=`FETCH_STORE_SUCCESS`
export const FETCH_STORE_FAIL=`FETCH_STORE_FAIL`
// AllStores
export const FETCH_STORES_SUCCESS = 'FETCH_STORES_SUCCESS';
export const FETCH_STORES_FAIL = 'FETCH_STORES_FAIL';

//FETCH COMMENTS
export const FETCH_COMMENTS_SUCCESS=`FETCH_COMMENTS_SUCCESS`
export const FETCH_COMMENTS_FAIL=`FETCH_COMMENTS_FAIL`
export const ADD_COMMENT_SUCCESS=`ADD_COMMENT_SUCCESS`
export const ADD_COMMENT_FAIL=`ADD_COMMENT_FAIL`
export const UPDATE_COMMENT_STATUS_SUCCESS =`UPDATE_COMMENT_STATUS_SUCCESS`  
export const UPDATE_COMMENT_STATUS_FAIL=`UPDATE_COMMENT_STATUS_FAIL`