export const DASHBOARD_PROFILE_DETAILS = `DASHBOARD_PROFILE_DETAILS`
export const DASHBOARD_COMMENTS=`DASHBOARD_COMMENTS`

export const DASHBOARD_PROFILE_DETAILS_FIRST = `DASHBOARD_PROFILE_DETAILS`
export const DASHBOARD_COMMENTS_FIRST=`DASHBOARD_COMMENTS`